const $=s=>document.querySelector(s), canvas=$('#game'),ctx=canvas.getContext('2d');
const W=960,H=768,T=16,keys=new Set();let mode='intro',previous=0,elapsed=0,fuel=100,dark=0,wood=0,pages=0,ritual=0,windows=0,generator=false,fear=0,angle=-1.57,lightning=0,storm=9,nextEnemy=15,toastTime=0,sound=false,audioCtx=null,ambient=null,heartbeat=0;
let player={x:480,y:397},camera={x:0,y:0},items=[],enemies=[],walls=[],decor=[],rng=Math.random;
const rand=(a,b)=>a+rng()*(b-a), pick=a=>a[Math.floor(rng()*a.length)];
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h)}
function build(){walls=[{x:16,y:16,w:928,h:16},{x:16,y:736,w:928,h:16},{x:16,y:16,w:16,h:736},{x:928,y:16,w:16,h:736}];
 for(const x of [320,640])for(let row=0;row<2;row++){let door= row*352+pick([128,176,224]);walls.push({x,y:32+row*352,w:16,h:door-(32+row*352)},{x,y:door+48,w:16,h:384+row*352-door-48});}
 for(let col=0;col<3;col++){let door=col*304+pick([112,176,208]);walls.push({x:32+col*304,y:368,w:door-(32+col*304),h:16},{x:door+48,y:368,w:336+col*304-door-48,h:16});}
 decor=[];for(let i=0;i<360;i++)decor.push({x:rand(35,925),y:rand(35,733),v:rand(0,1)});
 items=[{x:112,y:640,type:'generator'},{x:420,y:40,type:'window'},{x:554,y:40,type:'window'},{x:480,y:723,type:'exit'}];
 const spots=[];for(let row=0;row<2;row++)for(let col=0;col<3;col++)for(const [dx,dy] of [[70,95],[228,95],[85,254],[239,275]])spots.push({x:col*304+dx,y:row*352+dy});
 for(let i=spots.length-1;i>0;i--){let j=Math.floor(rng()*(i+1));[spots[i],spots[j]]=[spots[j],spots[i]];}
 ['ritual','ritual','ritual','wood','wood',...Array(12).fill('oil'),...Array(4).fill('note')].forEach(type=>items.push({...spots.pop(),type}));
 // A guaranteed first refill introduces exploration without a blind start.
 items.push({x:519,y:449,type:'oil'});
}
function reset(){elapsed=0;fuel=100;dark=0;wood=0;pages=0;ritual=0;windows=0;generator=false;fear=0;player={x:480,y:397};enemies=[];storm=9;nextEnemy=15;build();updateUI();}
function furniture(x,y,type){if(type==='shelf'){rect(x+2,y+3,62,23,'#080b08');rect(x,y,60,20,'#393324');rect(x+3,y+3,54,12,'#171c14');for(let i=0;i<12;i++){rect(x+4+i*4,y+4,3,10,['#666044','#3e4b36','#70503a','#80754e'][i%4]);}rect(x,y+17,60,3,'#554a31');}else if(type==='table'){rect(x+5,y+6,50,36,'#080b08');rect(x,y,48,32,'#423b28');rect(x+2,y+2,44,26,'#544a30');rect(x+6,y+5,36,1,'#6b5835');rect(x+10,y+8,9,11,'#9b9876');rect(x+11,y+9,6,1,'#5c6447');rect(x+32,y+8,4,7,'#918561');}else{rect(x+4,y+5,59,29,'#080b08');rect(x,y,56,26,'#333e2e');rect(x+5,y+5,46,17,'#46523a');rect(x+27,y+4,2,20,'#283524');rect(x-3,y+1,7,26,'#53583b');rect(x+52,y+1,7,26,'#53583b');}}
function drawWorld(){rect(0,0,W,H,'#20251b');for(let y=32;y<736;y+=16)for(let x=32;x<928;x+=32){let n=((x*13+y*7)%31);rect(x,y,31,15,n<12?'#303124':n<23?'#2a2d20':'#353526');rect(x+2,y+13,26,1,'#1c2219');if(n<9)rect(x+11,y+5,12,1,'#3b3a28');}
 // Worn carpets in the central hall and upstairs sitting room.
 for(const r of [{x:381,y:420,w:205,h:185},{x:382,y:120,w:205,h:172}]){rect(r.x,r.y,r.w,r.h,'#48432b');rect(r.x+3,r.y+3,r.w-6,r.h-6,'#242e24');rect(r.x+8,r.y+8,r.w-16,r.h-16,'#444333');rect(r.x+11,r.y+11,r.w-22,r.h-22,'#303729');for(let y=r.y+18;y<r.y+r.h-16;y+=16)for(let x=r.x+18;x<r.x+r.w-16;x+=16){rect(x,y,3,3,'#54543b');rect(x+4,y+3,3,3,'#404c32');}rect(r.x+20,r.y+r.h/2,r.w-40,1,'#606044');}
 decor.forEach(d=>{rect(d.x,d.y,d.v>.8?5:2,1,'#12190f55');if(d.v>.96){rect(d.x,d.y,6,2,'#73705344');rect(d.x+3,d.y-2,3,1,'#73705344');}});
 furniture(366,399,'shelf');furniture(562,502,'sofa');furniture(449,512,'table');furniture(373,634,'sofa');furniture(435,80,'shelf');furniture(560,214,'sofa');furniture(437,184,'table');furniture(42,47,'shelf');furniture(186,47,'shelf');furniture(119,180,'table');furniture(689,47,'shelf');furniture(756,179,'sofa');furniture(808,232,'table');furniture(699,410,'shelf');furniture(752,537,'table');furniture(56,413,'shelf');
 // Basement stairs and machinery.
 rect(43,560,70,67,'#151c16');for(let i=0;i<7;i++){rect(43,560+i*9,70,2,'#4a4a36');rect(43,563+i*9,70,2,'#252f22');}
 walls.forEach(w=>{rect(w.x+3,w.y+5,w.w,w.h,'#080d09');rect(w.x,w.y,w.w,w.h,'#424636');rect(w.x,w.y,w.w,3,'#60614b');rect(w.x,w.y+w.h-4,w.w,4,'#171f16');for(let y=w.y+7;y<w.y+w.h-3;y+=8)for(let x=w.x+4;x<w.x+w.w-2;x+=16)rect(x,y,10,1,'#313c2b');});
 // Cold window light and rain on the panes.
 [90,226,418,552,726,854].forEach(x=>{rect(x,17,29,14,'#151f1b');rect(x+2,20,24,9,'#576d5a');rect(x+13,18,2,14,'#1b271e');rect(x,24,29,2,'#1b271e');rect(x+5,33,21,2,'#60725a');});
 items.filter(i=>!i.used).forEach(i=>drawItem(i));
}
function drawItem(i){const{x,y,type}=i; if(type==='oil'){rect(x-4,y-5,8,11,'#8c743f');rect(x-2,y-8,4,3,'#b7a377');rect(x-2,y-2,4,5,'#d3a34c');}if(type==='wood'){rect(x-7,y-3,15,4,'#a47e49');rect(x-5,y+2,14,4,'#80603b');rect(x+3,y-3,1,4,'#3a3525');}if(type==='note'){rect(x-5,y-6,10,12,'#b2b18a');for(let j=0;j<3;j++)rect(x-3,y-3+j*3,6,1,'#626448');}if(type==='ritual'){ctx.strokeStyle='#adb4a0';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x,y-8);ctx.lineTo(x+6,y+5);ctx.lineTo(x-6,y+5);ctx.closePath();ctx.stroke();rect(x-1,y-2,2,3,'#dbb774');}if(type==='generator'){rect(x-14,y-11,28,23,'#555b46');rect(x-11,y-8,14,15,'#283529');for(let j=0;j<4;j++)rect(x-9,y-5+j*3,10,1,'#889078');rect(x+7,y-5,3,3,generator?'#b1d679':'#e2a256');rect(x-10,y+12,4,3,'#141c13');rect(x+8,y+12,4,3,'#141c13');}if(type==='window'&&i.sealed){rect(x-13,y-17,27,4,'#b68e56');rect(x-13,y-9,27,4,'#987546');}if(type==='exit'){rect(x-23,y-2,46,17,'#161e15');rect(x-20,y,40,15,'#5a4c31');rect(x,y,2,15,'#1b2317');rect(x-4,y+5,2,2,'#b2995c');}}
function drawPlayer(t){let walk=(keys.size&&mode==='playing')?Math.sin(t*14)*2:0;const{x,y}=player;rect(x-5,y+7,11,4,'#080c08');rect(x-4,y+3,3,7+walk,'#252b23');rect(x+2,y+3,3,7-walk,'#252b23');rect(x-5,y-5,11,11,'#6c7250');rect(x-3,y-4,5,9,'#8c8c61');rect(x-4,y-11,8,7,'#ab9b70');rect(x-5,y-12,9,3,'#423e2c');const tx=x+Math.cos(angle)*13,ty=y+Math.sin(angle)*13;rect(tx-1,ty,2,8,'#a78547');if(fuel>0){rect(tx-2,ty-4,5,5,'#e4a548');rect(tx-1,ty-7+Math.sin(t*20)*2,3,6,'#ffdb7f');rect(tx,ty-4,1,3,'#fff3b5');}ctx.strokeStyle='#a88b4866';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y,18,-Math.PI/2,-Math.PI/2+fuel/100*Math.PI*2);ctx.stroke();}
function render(t){const vW=480,vH=Math.round(480*canvas.clientHeight/canvas.clientWidth);if(canvas.width!==vW||canvas.height!==vH){canvas.width=vW;canvas.height=vH;}camera.x=Math.max(0,Math.min(W-vW,player.x-vW/2));camera.y=Math.max(0,Math.min(H-vH,player.y-vH/2));ctx.save();ctx.translate(-Math.floor(camera.x),-Math.floor(camera.y));drawWorld();drawPlayer(t);enemies.forEach(e=>{rect(e.x-5,e.y-10,10,22,'#080e09');rect(e.x-8,e.y-4,16,12,'#0d160e');rect(e.x-4,e.y-7,2,1,'#e4c28c');rect(e.x+3,e.y-7,2,1,'#e4c28c');});ctx.restore();const px=player.x-camera.x,py=player.y-camera.y;let radius=fuel>0?100+Math.sin(t*12)*3:17;if(storm<1.5)radius*=.65+Math.random()*.3;if(generator&&player.x<320&&player.y>384)radius=Math.max(radius,130);let g=ctx.createRadialGradient(px,py,12,px,py,radius*1.65);g.addColorStop(0,'rgba(3,8,4,0)');g.addColorStop(.38,'rgba(3,8,4,.10)');g.addColorStop(.67,'rgba(3,8,4,.65)');g.addColorStop(1,'rgba(2,6,3,.96)');ctx.fillStyle=g;ctx.fillRect(0,0,vW,vH);
 if(fuel>0){ctx.save();ctx.translate(px,py);ctx.rotate(angle);const glow=ctx.createRadialGradient(15,0,0,15,0,85);glow.addColorStop(0,'#e4ba5a10');glow.addColorStop(1,'#dab96500');ctx.fillStyle=glow;ctx.beginPath();ctx.moveTo(0,0);ctx.arc(0,0,110,-.55,.55);ctx.closePath();ctx.fill();ctx.restore();}
 if(lightning>0){rect(0,0,vW,vH,`rgba(186,206,186,${lightning*.7})`);const ex=px+55,ey=py-30;rect(ex-5,ey-22,10,35,'#101712');rect(ex-10,ey-12,20,19,'#101712');rect(ex-3,ey-19,2,2,'#e1e2cf');rect(ex+2,ey-19,2,2,'#e1e2cf');}
 if(fear>45){rect(0,Math.floor(t*83)%vH,vW,2,'#a67d6325');if(Math.random()<.03)rect(0,Math.random()*vH,vW,1,'#bbccaa33');}if(dark>0){rect(0,0,vW,vH,`rgba(120,18,12,${dark*.09})`);} }
function blocked(x,y){return walls.some(w=>x+6>w.x&&x-6<w.x+w.w&&y+7>w.y&&y-7<w.y+w.h);}
function nearby(){return items.filter(i=>!i.used&&!(i.type==='window'&&i.sealed)&&Math.hypot(player.x-i.x,player.y-i.y)<31).sort((a,b)=>Math.hypot(player.x-a.x,player.y-a.y)-Math.hypot(player.x-b.x,player.y-b.y))[0];}
const labels={oil:'Reabastecer a tocha',wood:'Pegar tábua',note:'Ler página',ritual:'Recolher fragmento',generator:'Ligar gerador',window:'Selar janela · 1 tábua',exit:'Abrir a porta'};
function interact(){if(mode!=='playing')return;let i=nearby();if(!i)return;tone(230,.07,.025);switch(i.type){case'oil':if(fuel>85){notify('A tocha ainda está cheia. Guarde este óleo para depois.');return;}fuel=Math.min(100,fuel+40);i.used=true;notify('Óleo encontrado. A chama respira novamente.');break;case'wood':wood++;i.used=true;notify('Uma tábua. As janelas ficam ao norte do hall.');break;case'ritual':ritual++;i.used=true;fear=Math.max(0,fear-15);notify(`Fragmento do ritual ${ritual}/3. Algo recuou nas sombras.`);break;case'generator':if(generator){notify('O gerador está funcionando.');return;}generator=true;notify('O gerador voltou à vida. O porão agora tem luz.');break;case'window':if(!wood){notify('Você precisa encontrar uma tábua de madeira.');return;}wood--;windows++;i.sealed=true;notify('Janela selada. O vento perdeu uma entrada.');break;case'note':pages++;i.used=true;showModal('UMA PÁGINA DO DIÁRIO',`Registro ${pick(['14 de outubro','3 de novembro','21 de dezembro'])}`,`<p>“${pick(['Mamãe disse para não contar os passos no corredor. Hoje, eles pararam na minha porta.','O gerador fica no porão, a sudoeste. A coisa odeia quando a máquina acorda.','Queimei todas as fotografias. Pela manhã, havia mais uma na parede.','Três partes do símbolo. Duas janelas. Uma saída ao sul. Foi o que ele escreveu antes de desaparecer.'])}”</p><p>A tinta ainda está úmida.</p>`,'VOLTAR À MANSÃO');if(Math.random()<.35){nextEnemy=1;notify('O papel se rasga. Alguma coisa ouviu.');}break;case'exit':if(elapsed>=360&&generator&&windows===2&&ritual===3){finish(true);}else notify(elapsed<360?'A porta só abrirá ao amanhecer. Complete as tarefas.':'O sol nasceu, mas o selo permanece. Conclua as tarefas.');break;}updateUI();}
function notify(text){$('#toast').textContent=text;$('#toast').style.display='block';toastTime=5;}
function updateUI(){let minutes=Math.min(360,Math.floor(elapsed));$('#clock').innerHTML=`${String(Math.floor(minutes/60)).padStart(2,'0')}<span>:</span>${String(minutes%60).padStart(2,'0')}`;$('#fuel-label').textContent=`${Math.ceil(fuel)}%`;$('#fuel-bar').style.width=`${fuel}%`;$('#fuel-time').textContent=fuel<25?'CHAMA FRACA':'CHAMA ESTÁVEL';$('#wood').textContent=wood;$('#pages').textContent=pages;$('#window-count').textContent=`${windows} / 2`;$('#window-progress').style.width=`${windows*50}%`;$('#ritual-count').textContent=`${ritual} / 3`;document.querySelectorAll('.fragments span').forEach((e,j)=>e.classList.toggle('found',j<ritual));$('#task-gen .task-state').textContent=generator?'CONCLUÍDO':'PENDENTE';$('#task-gen').classList.toggle('done',generator);$('#task-windows').classList.toggle('done',windows===2);$('#task-ritual').classList.toggle('done',ritual===3);$('#room').textContent=player.y<368?(player.x<320?'BIBLIOTECA':player.x<640?'SALA PRINCIPAL':'QUARTO LESTE'):(player.x<320?'PORÃO':player.x<640?'HALL DE ENTRADA':'SALA DE JANTAR');}
function step(dt){elapsed+=dt;fuel=Math.max(0,fuel-dt*(windows===2?.25:.32));const safe=generator&&player.x<320&&player.y>384;dark=fuel<=0&&!safe?dark+dt:0;if(dark>=3){finish(false,'A chama morreu. E a escuridão encontrou você.');return;}let dx=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),dy=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);let length=Math.hypot(dx,dy)||1;let nx=player.x+dx/length*67*dt,ny=player.y+dy/length*67*dt;if(!blocked(nx,player.y))player.x=nx;if(!blocked(player.x,ny))player.y=ny;
 storm-=dt;lightning=Math.max(0,lightning-dt*3);if(storm<=0){storm=rand(14,28);lightning=.8;tone(45,1,.13,'sawtooth');if(windows<2)notify('O vento atravessa a casa. Proteja sua chama.');}nextEnemy-=dt;if(nextEnemy<=0){nextEnemy=rand(18,32);let a=rand(0,Math.PI*2);enemies.push({x:player.x+Math.cos(a)*105,y:player.y+Math.sin(a)*105,exposure:0});}
 for(const e of enemies){let a=Math.atan2(e.y-player.y,e.x-player.x),difference=Math.atan2(Math.sin(a-angle),Math.cos(a-angle));if(fuel>0&&Math.abs(difference)<.55){e.exposure+=dt;e.x+=Math.cos(a)*35*dt;e.y+=Math.sin(a)*35*dt;}else{e.x-=Math.cos(a)*12*dt;e.y-=Math.sin(a)*12*dt;e.exposure=Math.max(0,e.exposure-dt*.2);}if(Math.hypot(e.x-player.x,e.y-player.y)<12){finish(false,'Você ignorou os olhos na borda da luz.');return;}}enemies=enemies.filter(e=>e.exposure<1.3&&Math.hypot(e.x-player.x,e.y-player.y)<230);fear=Math.max(0,Math.min(100,fear+(enemies.length?5:-2)*dt));heartbeat-=dt;if(heartbeat<=0){heartbeat=fear>40?.48:1.1;if(fear>10||fuel<25)tone(58,.13,.07);}
 if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('#toast').style.display='none';}let item=nearby();$('#interact').textContent=item?`[ E ] ${labels[item.type]}`:'';$('#status').textContent=dark>0?`SEM LUZ · ${(3-dark).toFixed(1)}s`:enemies.length?'ALGO OBSERVA VOCÊ':fuel<25?'ENCONTRE COMBUSTÍVEL':elapsed>=360?'O SOL NASCEU. VÁ ATÉ A SAÍDA.':'MANTENHA A CHAMA ACESA';if(elapsed>=360&&generator&&windows===2&&ritual===3&&Math.hypot(player.x-480,player.y-723)<35)finish(true);updateUI();}
function frame(ms){const dt=Math.min((ms-previous)/1000,.05);previous=ms;if(mode==='playing')step(dt);render(ms/1000);requestAnimationFrame(frame);}
function start(){reset();mode='playing';$('#intro').classList.add('hidden');$('#status').textContent='MANTENHA A CHAMA ACESA';notify('Explore com WASD. Aponte o mouse para afastar as sombras.');if(sound)startAudio();}
function tone(freq,duration,volume,type='sine'){if(!sound||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+duration);}
function startAudio(){if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();let buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;let source=audioCtx.createBufferSource();source.buffer=buffer;source.loop=true;let filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=700;ambient=audioCtx.createGain();ambient.gain.value=.045;source.connect(filter);filter.connect(ambient);ambient.connect(audioCtx.destination);source.start();}audioCtx.resume();}
let resumeMode='intro',modalCallback=null;function showModal(eyebrow,title,body,action='CONTINUAR',callback=null){resumeMode=mode;mode='paused';keys.clear();$('#modal-eyebrow').textContent=eyebrow;$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal-action').innerHTML=action+' <span>→</span>';modalCallback=callback;$('#modal').showModal();}
function closeModal(){ $('#modal').close();mode=resumeMode;if(modalCallback){let f=modalCallback;modalCallback=null;f();}}
function pause(){if(mode==='playing')showModal('RESPIRE. POR ENQUANTO.','A noite pode esperar.','<p>O tempo e o combustível estão congelados. Quando estiver pronto, volte à mansão.</p>','CONTINUAR');}
function finish(win,reason){mode=win?'won':'dead';$('#interact').textContent='';showModal(win?'06:00 · AMANHECER':'A MANSÃO GUARDA MAIS UM SEGREDO',win?'Você viu o amanhecer.':'A noite ficou com você.',`<p>${win?'O símbolo se desfez. A porta se abriu. Pela primeira vez em horas, o silêncio é apenas silêncio.':reason}</p><p>Tempo sobrevivido: ${$('#clock').textContent} · Fragmentos: ${ritual}/3 · Páginas: ${pages}</p>`,'TENTAR UMA NOVA NOITE',start);}
$('#start').onclick=start;$('#pause').onclick=pause;$('#audio').onclick=()=>{sound=!sound;if(sound)startAudio();else audioCtx?.suspend();$('#audio').innerHTML=sound?'◖)) <span>SOM LIGADO</span>':'◖)) <span>SOM DESLIGADO</span>';};$('#help').onclick=()=>showModal('MANUAL DE SOBREVIVÊNCIA','Não deixe a luz morrer.','<p><b>WASD ou setas</b> para andar. <b>Mouse</b> para apontar a tocha. <b>E</b> para interagir. <b>Esc</b> para pausar.</p><p>Encontre óleo nos cômodos e aponte a luz para os olhos na escuridão até desaparecerem.</p><p><b>01.</b> Ligue o gerador no porão, a sudoeste.<br><b>02.</b> Encontre duas tábuas e sele as janelas ao norte da sala principal.<br><b>03.</b> Colete três fragmentos e vá à porta ao sul do hall às 06:00.</p><p>A noite dura <b>6 minutos reais</b>. Itens e passagens mudam a cada partida. Sem combustível, você tem 3 segundos — exceto na área iluminada pelo gerador.</p>','ENTENDI');$('#modal-action').onclick=closeModal;$('#close-modal').onclick=closeModal;$('#modal').addEventListener('cancel',e=>{e.preventDefault();closeModal();});
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();keys.add(e.key.toLowerCase());if(e.key.toLowerCase()==='e'&&!e.repeat)interact();if(e.key==='Escape'&&!$('#modal').open)pause();});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});canvas.addEventListener('mousemove',e=>{const r=canvas.getBoundingClientRect();angle=Math.atan2((e.clientY-r.top)*canvas.height/r.height+camera.y-player.y,(e.clientX-r.left)*canvas.width/r.width+camera.x-player.x);});
reset();requestAnimationFrame(frame);
